"""create mouse table

Revision ID: d8a73bc96f11
Revises: 
Create Date: 2026-10-01 15:06:45.494078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a73bc96f11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('sensor', sa.String(length=80), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('connection', sa.String(length=20), nullable=False),
    sa.Column('polling_rate_hz', sa.Integer(), nullable=True),
    sa.Column('switch_type', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model', name='uq_mouse_brand_model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouse')
    # ### end Alembic commands ###
